spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8091"
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-accesorios
              uri: lb://ms-accesorios
              predicates:
                Path=/api/accesorios/**
            - id: ms-clientes
              uri: lb://ms-clientes
              predicates:
                - Path=/api/clientes/**
            - id: ms-herramientas
              uri: lb://ms-herramientas
              predicates:
                - Path=/api/herramientas/**
            - id: ms-melamine
              uri: lb://ms-melamine
              predicates:
                - Path=/api/melamine/**
            - id: ms-proveedores
              uri: lb://ms-proveedores
              predicates:
                - Path=/api/proveedores/**, /api/categoria-proveedor/**
            - id: ms-proyectos
              uri: lb://ms-proyectos
              predicates:
                - Path=/api/proyectos/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true